// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_workgroup.proto

#ifndef PROTOBUF_message_5fworkgroup_2eproto__INCLUDED
#define PROTOBUF_message_5fworkgroup_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "message_common.pb.h"
// @@protoc_insertion_point(includes)

namespace rpc {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_message_5fworkgroup_2eproto();
void protobuf_AssignDesc_message_5fworkgroup_2eproto();
void protobuf_ShutdownFile_message_5fworkgroup_2eproto();

class WorkGroupsListRequest;
class WorkGroupsListResponse;

// ===================================================================

class WorkGroupsListRequest : public ::google::protobuf::Message {
 public:
  WorkGroupsListRequest();
  virtual ~WorkGroupsListRequest();

  WorkGroupsListRequest(const WorkGroupsListRequest& from);

  inline WorkGroupsListRequest& operator=(const WorkGroupsListRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WorkGroupsListRequest& default_instance();

  void Swap(WorkGroupsListRequest* other);

  // implements Message ----------------------------------------------

  inline WorkGroupsListRequest* New() const { return New(NULL); }

  WorkGroupsListRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const WorkGroupsListRequest& from);
  void MergeFrom(const WorkGroupsListRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(WorkGroupsListRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string session_id = 1;
  bool has_session_id() const;
  void clear_session_id();
  static const int kSessionIdFieldNumber = 1;
  const ::std::string& session_id() const;
  void set_session_id(const ::std::string& value);
  void set_session_id(const char* value);
  void set_session_id(const char* value, size_t size);
  ::std::string* mutable_session_id();
  ::std::string* release_session_id();
  void set_allocated_session_id(::std::string* session_id);

  // optional .rpc.Filter filter = 2;
  bool has_filter() const;
  void clear_filter();
  static const int kFilterFieldNumber = 2;
  ::rpc::Filter filter() const;
  void set_filter(::rpc::Filter value);

  // @@protoc_insertion_point(class_scope:rpc.WorkGroupsListRequest)
 private:
  inline void set_has_session_id();
  inline void clear_has_session_id();
  inline void set_has_filter();
  inline void clear_has_filter();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr session_id_;
  int filter_;
  friend void  protobuf_AddDesc_message_5fworkgroup_2eproto();
  friend void protobuf_AssignDesc_message_5fworkgroup_2eproto();
  friend void protobuf_ShutdownFile_message_5fworkgroup_2eproto();

  void InitAsDefaultInstance();
  static WorkGroupsListRequest* default_instance_;
};
// -------------------------------------------------------------------

class WorkGroupsListResponse : public ::google::protobuf::Message {
 public:
  WorkGroupsListResponse();
  virtual ~WorkGroupsListResponse();

  WorkGroupsListResponse(const WorkGroupsListResponse& from);

  inline WorkGroupsListResponse& operator=(const WorkGroupsListResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WorkGroupsListResponse& default_instance();

  void Swap(WorkGroupsListResponse* other);

  // implements Message ----------------------------------------------

  inline WorkGroupsListResponse* New() const { return New(NULL); }

  WorkGroupsListResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const WorkGroupsListResponse& from);
  void MergeFrom(const WorkGroupsListResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(WorkGroupsListResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 error_code = 1;
  bool has_error_code() const;
  void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  ::google::protobuf::int32 error_code() const;
  void set_error_code(::google::protobuf::int32 value);

  // repeated .rpc.WorkGroupInfo workgroup_info_list = 2;
  int workgroup_info_list_size() const;
  void clear_workgroup_info_list();
  static const int kWorkgroupInfoListFieldNumber = 2;
  const ::rpc::WorkGroupInfo& workgroup_info_list(int index) const;
  ::rpc::WorkGroupInfo* mutable_workgroup_info_list(int index);
  ::rpc::WorkGroupInfo* add_workgroup_info_list();
  ::google::protobuf::RepeatedPtrField< ::rpc::WorkGroupInfo >*
      mutable_workgroup_info_list();
  const ::google::protobuf::RepeatedPtrField< ::rpc::WorkGroupInfo >&
      workgroup_info_list() const;

  // optional int64 last_event_id = 3;
  bool has_last_event_id() const;
  void clear_last_event_id();
  static const int kLastEventIdFieldNumber = 3;
  ::google::protobuf::int64 last_event_id() const;
  void set_last_event_id(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:rpc.WorkGroupsListResponse)
 private:
  inline void set_has_error_code();
  inline void clear_has_error_code();
  inline void set_has_last_event_id();
  inline void clear_has_last_event_id();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::rpc::WorkGroupInfo > workgroup_info_list_;
  ::google::protobuf::int64 last_event_id_;
  ::google::protobuf::int32 error_code_;
  friend void  protobuf_AddDesc_message_5fworkgroup_2eproto();
  friend void protobuf_AssignDesc_message_5fworkgroup_2eproto();
  friend void protobuf_ShutdownFile_message_5fworkgroup_2eproto();

  void InitAsDefaultInstance();
  static WorkGroupsListResponse* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// WorkGroupsListRequest

// optional string session_id = 1;
inline bool WorkGroupsListRequest::has_session_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void WorkGroupsListRequest::set_has_session_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void WorkGroupsListRequest::clear_has_session_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void WorkGroupsListRequest::clear_session_id() {
  session_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_session_id();
}
inline const ::std::string& WorkGroupsListRequest::session_id() const {
  // @@protoc_insertion_point(field_get:rpc.WorkGroupsListRequest.session_id)
  return session_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void WorkGroupsListRequest::set_session_id(const ::std::string& value) {
  set_has_session_id();
  session_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:rpc.WorkGroupsListRequest.session_id)
}
inline void WorkGroupsListRequest::set_session_id(const char* value) {
  set_has_session_id();
  session_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:rpc.WorkGroupsListRequest.session_id)
}
inline void WorkGroupsListRequest::set_session_id(const char* value, size_t size) {
  set_has_session_id();
  session_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:rpc.WorkGroupsListRequest.session_id)
}
inline ::std::string* WorkGroupsListRequest::mutable_session_id() {
  set_has_session_id();
  // @@protoc_insertion_point(field_mutable:rpc.WorkGroupsListRequest.session_id)
  return session_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* WorkGroupsListRequest::release_session_id() {
  clear_has_session_id();
  return session_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void WorkGroupsListRequest::set_allocated_session_id(::std::string* session_id) {
  if (session_id != NULL) {
    set_has_session_id();
  } else {
    clear_has_session_id();
  }
  session_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), session_id);
  // @@protoc_insertion_point(field_set_allocated:rpc.WorkGroupsListRequest.session_id)
}

// optional .rpc.Filter filter = 2;
inline bool WorkGroupsListRequest::has_filter() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void WorkGroupsListRequest::set_has_filter() {
  _has_bits_[0] |= 0x00000002u;
}
inline void WorkGroupsListRequest::clear_has_filter() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void WorkGroupsListRequest::clear_filter() {
  filter_ = 0;
  clear_has_filter();
}
inline ::rpc::Filter WorkGroupsListRequest::filter() const {
  // @@protoc_insertion_point(field_get:rpc.WorkGroupsListRequest.filter)
  return static_cast< ::rpc::Filter >(filter_);
}
inline void WorkGroupsListRequest::set_filter(::rpc::Filter value) {
  assert(::rpc::Filter_IsValid(value));
  set_has_filter();
  filter_ = value;
  // @@protoc_insertion_point(field_set:rpc.WorkGroupsListRequest.filter)
}

// -------------------------------------------------------------------

// WorkGroupsListResponse

// optional int32 error_code = 1;
inline bool WorkGroupsListResponse::has_error_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void WorkGroupsListResponse::set_has_error_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void WorkGroupsListResponse::clear_has_error_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void WorkGroupsListResponse::clear_error_code() {
  error_code_ = 0;
  clear_has_error_code();
}
inline ::google::protobuf::int32 WorkGroupsListResponse::error_code() const {
  // @@protoc_insertion_point(field_get:rpc.WorkGroupsListResponse.error_code)
  return error_code_;
}
inline void WorkGroupsListResponse::set_error_code(::google::protobuf::int32 value) {
  set_has_error_code();
  error_code_ = value;
  // @@protoc_insertion_point(field_set:rpc.WorkGroupsListResponse.error_code)
}

// repeated .rpc.WorkGroupInfo workgroup_info_list = 2;
inline int WorkGroupsListResponse::workgroup_info_list_size() const {
  return workgroup_info_list_.size();
}
inline void WorkGroupsListResponse::clear_workgroup_info_list() {
  workgroup_info_list_.Clear();
}
inline const ::rpc::WorkGroupInfo& WorkGroupsListResponse::workgroup_info_list(int index) const {
  // @@protoc_insertion_point(field_get:rpc.WorkGroupsListResponse.workgroup_info_list)
  return workgroup_info_list_.Get(index);
}
inline ::rpc::WorkGroupInfo* WorkGroupsListResponse::mutable_workgroup_info_list(int index) {
  // @@protoc_insertion_point(field_mutable:rpc.WorkGroupsListResponse.workgroup_info_list)
  return workgroup_info_list_.Mutable(index);
}
inline ::rpc::WorkGroupInfo* WorkGroupsListResponse::add_workgroup_info_list() {
  // @@protoc_insertion_point(field_add:rpc.WorkGroupsListResponse.workgroup_info_list)
  return workgroup_info_list_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::rpc::WorkGroupInfo >*
WorkGroupsListResponse::mutable_workgroup_info_list() {
  // @@protoc_insertion_point(field_mutable_list:rpc.WorkGroupsListResponse.workgroup_info_list)
  return &workgroup_info_list_;
}
inline const ::google::protobuf::RepeatedPtrField< ::rpc::WorkGroupInfo >&
WorkGroupsListResponse::workgroup_info_list() const {
  // @@protoc_insertion_point(field_list:rpc.WorkGroupsListResponse.workgroup_info_list)
  return workgroup_info_list_;
}

// optional int64 last_event_id = 3;
inline bool WorkGroupsListResponse::has_last_event_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void WorkGroupsListResponse::set_has_last_event_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void WorkGroupsListResponse::clear_has_last_event_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void WorkGroupsListResponse::clear_last_event_id() {
  last_event_id_ = GOOGLE_LONGLONG(0);
  clear_has_last_event_id();
}
inline ::google::protobuf::int64 WorkGroupsListResponse::last_event_id() const {
  // @@protoc_insertion_point(field_get:rpc.WorkGroupsListResponse.last_event_id)
  return last_event_id_;
}
inline void WorkGroupsListResponse::set_last_event_id(::google::protobuf::int64 value) {
  set_has_last_event_id();
  last_event_id_ = value;
  // @@protoc_insertion_point(field_set:rpc.WorkGroupsListResponse.last_event_id)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace rpc

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_message_5fworkgroup_2eproto__INCLUDED
